### ISSUE TITLE
pod 不成功

### ISSUE THREAD

**Issue by zyg-github** [hhtczengjing/leveldb-pd#1]
Unable to find a specification for 'leveled-pd'. 
不知道为什么？
求解 谢谢！

**Comment by hhtczengjing** [comment]
不好意思啊，我这个库没有提交到CocoaPods,可以使用
pod 'leveldb-pd', :git => 'https://github.com/hhtczengjing/leveldb-pd.git', :tag => ‘0.1.0’
的方式进行集成。
